### ISSUE TITLE
I want to contribute + Change the sensor ?

### ISSUE THREAD

**Issue by devshank3** [Ankou-Research-Institute/3D-fish-tracker#3]
Hello @tomoshi0809 ,

Its exciting to see this 3D tracker.
I'm an Computer Vision enthusiast, I have an SR305 sensor which seems to work for 3D tracking of objects 
under water. I can contribute to this project and share some ideas if you are interested.

D435 projects larger IR dots patterns for near objects, may be the pattern size is larger than the fish you want to track.
And generally D435 is not good for near range and for glass & water.

**Comment by tomoshi0809** [comment]
I really appreciate your comment.
I'm really excited to hear that there is a product by Intel, which can capture an object under water.
But...unfortunately, this project is now suspended because the fishes passed away.
I'm so glad if you contribute when we restart this project !
